"""
OpenAI Codex Adapter — generates AGENTS.md (hooks not supported)

AGENTS.md structure:
  [project header — written once on first create, never touched again]

  <!-- amk:start -->
  <!-- GENERATED by agent-memory-kit. DO NOT EDIT MANAGED BLOCK DIRECTLY. -->
  [managed memory protocol + architecture ref + conventions]
  <!-- amk:end -->

  [custom content outside sentinels is preserved across regenerations]

Note: Hermes also reads AGENTS.md. The hermes adapter produces a superset
(with skills note + memory mirroring footer). If you use both Codex and Hermes,
run the hermes adapter (or `generate.py all`, which runs codex then hermes so
hermes wins).
"""
from pathlib import Path

from .utils import write_managed_section, check_managed_section, build_memory_discipline


_MANAGED_TEMPLATE = """\
## Memory System

This project uses a file-based memory system to maintain context across sessions.

### On Session Start

Read `memory/semantic.md` ONCE to load project context before answering.

### On Every Turn

The preprompt hook handles reading `memory/working.md`.

### Task Files

Only load `/dev/[task]/*` files when actively working on that task.

### MCP Efficiency

Before calling any MCP tool to retrieve information, first check if that information might exist in `memory/semantic.md` or `dev/[task]/context.md` — local files are cheaper than remote MCP queries.

### Keep Context Minimal

Do not speculatively load files "just in case".

### Mid-Session Drift

If reasoning becomes uncertain or inconsistent with prior context, re-read `memory/semantic.md` before continuing.

{memory_discipline}

---

## Architecture

Before implementing a feature, read `{arch_file}`. It is the canonical record of architectural principles, load-bearing assumptions, and planned capabilities — not current build state (that lives in `memory/semantic.md`).

---

## Key conventions

{conventions_md}
"""


def referenced_memory_files() -> list[str]:
    """Return the set of .md files this adapter's Memory Discipline references."""
    return [
        "memory/semantic.md",
        "memory/working.md",
        "DECISIONS.md",
        "dev/[task]/context.md",
    ]


def _build_managed_content(config: dict) -> str:
    """Build the managed-section content from config."""
    arch_file = config.get("architecture", {}).get("file", "vision.md")
    conventions = config.get("conventions", [])
    conventions_md = (
        "\n".join(f"- {c}" for c in conventions) if conventions else ""
    )
    return _MANAGED_TEMPLATE.format(
        arch_file=arch_file,
        conventions_md=conventions_md,
        memory_discipline=build_memory_discipline(config, arch_file),
    )


def generate(project_root: Path, config: dict) -> str:
    project = config["project"]
    managed_content = _build_managed_content(config)
    header = (
        f"# Project Context — {project['name']}\n\n"
        f"**{project['name']}** is {project['description']}"
    )

    agents_md_status = write_managed_section(
        project_root / "AGENTS.md", header, managed_content, "AGENTS.md"
    )

    return (
        "Codex configuration generated:\n"
        f"{agents_md_status}\n\n"
        "Note: Codex does not support hooks. Memory loading relies on the agent reading AGENTS.md at session start.\n"
        "Note: If you also use Hermes, run `generate.py hermes` instead — the hermes AGENTS.md is a superset.\n"
        "  Custom content outside <!-- amk:start/end --> is preserved."
    )


# ── Check mode ────────────────────────────────────────────────────────────────


def check(project_root: Path, config: dict) -> list[str]:
    """Return drift diffs for all managed files (empty if no drift)."""
    managed_content = _build_managed_content(config)
    result = check_managed_section(
        project_root / "AGENTS.md", managed_content, "AGENTS.md (codex)"
    )
    return [result] if result else []
