"""
Cursor IDE Adapter — generates .cursor/rules/memory.mdc with auto-attach

memory.mdc structure:
  ---
  description: Memory system...
  alwaysApply: true
  ---

  [markdown body — written once on first create]

  <!-- amk:start -->
  <!-- GENERATED by agent-memory-kit. DO NOT EDIT MANAGED BLOCK DIRECTLY. -->
  [managed memory protocol + architecture ref + conventions]
  <!-- amk:end -->

  [custom content outside sentinels is preserved across regenerations]

.cursorignore is fully generated.
"""
from pathlib import Path

from .utils import (
    write_managed_section,
    check_managed_section,
    check_fully_generated,
    build_memory_discipline,
)


_MANAGED_TEMPLATE = """\
## Memory System

This project uses a file-based memory system. Follow these rules:

### Session Startup

1. Read `memory/semantic.md` ONCE at session start to load project context
2. Read `memory/working.md` to understand current task state

### On Every Turn

The preprompt hook handles reading `memory/working.md`.

### Task Files

Only load `/dev/[task]/*` files when actively working on that task.

### MCP Efficiency

Before calling any MCP tool to retrieve information, first check if that information might exist in `memory/semantic.md` or `dev/[task]/context.md` — local files are cheaper than remote MCP queries.

### Keep Context Minimal

Do not speculatively load files "just in case".

### Mid-Session Drift

If reasoning becomes uncertain or inconsistent with prior context, re-read `memory/semantic.md` before continuing.

{memory_discipline}

### Architecture Reference

Before implementing a feature, read `{arch_file}`. It is the canonical record of architectural principles, load-bearing assumptions, and planned capabilities — not current build state (that lives in `memory/semantic.md`).

## Conventions

{conventions_md}
"""


_CURSOR_FRONTMATTER = (
    "---\n"
    "description: Memory system for cross-session context\n"
    "alwaysApply: true\n"
    "---\n"
)

_CURSOR_HEADER = "# Memory System"


def referenced_memory_files() -> list[str]:
    """Return the set of .md files this adapter's Memory Discipline references."""
    return [
        "memory/semantic.md",
        "memory/working.md",
        "DECISIONS.md",
    ]


def _build_managed_content(config: dict) -> str:
    """Build the managed-section content from config."""
    arch_file = config.get("architecture", {}).get("file", "vision.md")
    conventions = config.get("conventions", [])
    conventions_md = "\n".join(f"- {c}" for c in conventions) if conventions else ""
    return _MANAGED_TEMPLATE.format(
        arch_file=arch_file,
        conventions_md=conventions_md,
        memory_discipline=build_memory_discipline(config, arch_file),
    )


def _build_cursorignore() -> str:
    """Build .cursorignore content."""
    return (
        "# Generated by agent-memory-kit. Do not edit directly.\n"
        "# Generated output — not source\n"
        "output/\n"
        ".cursor/history/\n"
    )


def generate(project_root: Path, config: dict) -> str:
    """Generate Cursor IDE configuration."""
    managed_content = _build_managed_content(config)

    cursor_dir = project_root / ".cursor"
    cursor_dir.mkdir(exist_ok=True)
    rules_dir = cursor_dir / "rules"
    rules_dir.mkdir(exist_ok=True)

    # memory.mdc — sentinel-managed with YAML frontmatter preserved
    mdc_status = write_managed_section(
        rules_dir / "memory.mdc",
        _CURSOR_HEADER,
        managed_content,
        ".cursor/rules/memory.mdc",
        frontmatter=_CURSOR_FRONTMATTER,
    )

    # .cursorignore — fully generated
    cursorignore_content = _build_cursorignore()
    (project_root / ".cursorignore").write_text(cursorignore_content)

    return (
        "Cursor configuration generated:\n"
        f"{mdc_status}\n"
        "  - .cursorignore"
    )


# ── Check mode ────────────────────────────────────────────────────────────────


def check(project_root: Path, config: dict) -> list[str]:
    """Return drift diffs for all managed/generated files (empty if no drift)."""
    diffs = []

    managed_content = _build_managed_content(config)
    r = check_managed_section(
        project_root / ".cursor" / "rules" / "memory.mdc",
        managed_content,
        ".cursor/rules/memory.mdc",
    )
    if r:
        diffs.append(r)

    cursorignore_expected = _build_cursorignore()
    r = check_fully_generated(
        project_root / ".cursorignore",
        cursorignore_expected,
        ".cursorignore",
    )
    if r:
        diffs.append(r)

    return diffs
