"""
Gemini CLI Adapter — generates GEMINI.md + sub-directory context files

GEMINI.md structure:
  [project header — written once on first create, never touched again]

  <!-- amk:start -->
  <!-- GENERATED by agent-memory-kit. DO NOT EDIT MANAGED BLOCK DIRECTLY. -->
  [managed memory protocol + architecture ref + conventions]
  <!-- amk:end -->

  [custom content outside sentinels is preserved across regenerations]
"""
from pathlib import Path

from .utils import write_managed_section, check_managed_section, check_fully_generated, build_memory_discipline


_MANAGED_TEMPLATE = """\
## Memory System

This project uses a file-based memory system. Treat it as authoritative.

### On Session Start

Read `memory/semantic.md` ONCE to load project context before answering.

### On Every Turn

The preprompt hook handles reading `memory/working.md`.

### Task Files

Only load `/dev/[task]/*` files when actively working on that task.

### Keep Context Minimal

Do not speculatively load files "just in case".

### Mid-Session Drift

If reasoning becomes uncertain or inconsistent with prior context, re-read `memory/semantic.md` before continuing.

{memory_discipline}

---

## Architecture

Before implementing a feature, read `{arch_file}`. It is the canonical record of architectural principles, load-bearing assumptions, and planned capabilities — not current build state (that lives in `memory/semantic.md`).

---

## Key conventions

{conventions_md}
"""


def referenced_memory_files() -> list[str]:
    """Return the set of .md files this adapter's Memory Discipline references."""
    return [
        "memory/semantic.md",
        "memory/working.md",
        "DECISIONS.md",
        "dev/[task]/context.md",
    ]


def _build_managed_content(config: dict) -> str:
    """Build the managed-section content from config."""
    arch_file = config.get("architecture", {}).get("file", "vision.md")
    conventions = config.get("conventions", [])
    conventions_md = "\n".join(f"- {c}" for c in conventions) if conventions else ""
    return _MANAGED_TEMPLATE.format(
        arch_file=arch_file,
        conventions_md=conventions_md,
        memory_discipline=build_memory_discipline(config, arch_file),
    )


def _build_context_md() -> str:
    """Build .gemini/context.md content."""
    return (
        "<!-- GENERATED by agent-memory-kit. DO NOT EDIT DIRECTLY. -->\n\n"
        "# Gemini CLI Context\n\n"
        "This project uses a shared memory system in the `memory/` directory:\n\n"
        "- `memory/semantic.md` — project knowledge (read at session start)\n"
        "- `memory/working.md` — current task state (read every turn)\n"
        "- `dev/[task]/` — active task context\n\n"
        "See `GEMINI.md` for full integration details.\n"
    )


def generate(project_root: Path, config: dict) -> str:
    """Generate Gemini CLI configuration."""
    project = config["project"]
    managed_content = _build_managed_content(config)
    header = (
        f"# Project Context — {project['name']}\n\n"
        f"**{project['name']}** is {project['description']}"
    )

    gemini_status = write_managed_section(
        project_root / "GEMINI.md", header, managed_content, "GEMINI.md"
    )

    gemini_dir = project_root / ".gemini"
    gemini_dir.mkdir(exist_ok=True)
    context_content = _build_context_md()
    (gemini_dir / "context.md").write_text(context_content)

    return (
        "Gemini CLI configuration generated:\n"
        f"{gemini_status}\n"
        "  - .gemini/context.md"
    )


# ── Check mode ────────────────────────────────────────────────────────────────


def check(project_root: Path, config: dict) -> list[str]:
    """Return drift diffs for all managed/generated files (empty if no drift)."""
    diffs = []

    managed_content = _build_managed_content(config)
    r = check_managed_section(
        project_root / "GEMINI.md", managed_content, "GEMINI.md"
    )
    if r:
        diffs.append(r)

    context_expected = _build_context_md()
    r = check_fully_generated(
        project_root / ".gemini" / "context.md",
        context_expected,
        ".gemini/context.md",
    )
    if r:
        diffs.append(r)

    return diffs
