"""
Hermes Agent Adapter — generates AGENTS.md (superset of the Codex adapter)

AGENTS.md structure:
  [project header — written once on first create, never touched again]

  <!-- amk:start -->
  <!-- GENERATED by agent-memory-kit. DO NOT EDIT MANAGED BLOCK DIRECTLY. -->
  [managed memory protocol + architecture ref + conventions + hermes footer]
  <!-- amk:end -->

  [custom content outside sentinels — Hermes profile details, PM skills,
   two-layer LLM notes, etc. — is preserved across regenerations]

Hermes (Nous Research) reads AGENTS.md as workspace-level context and supports
the agentskills.io skill frontmatter standard natively via its /skills browser.

NOTE: Both this adapter and the Codex adapter write AGENTS.md. This version is
a superset. Codex reads the result fine. If you run both agents, use this adapter
(or run `generate.py all`, which runs codex then hermes so hermes wins).
"""
from pathlib import Path

from .utils import write_managed_section, check_managed_section, build_memory_discipline


_MANAGED_TEMPLATE = """\
## Memory System

This project uses a file-based memory system to maintain context across sessions.

### On Session Start

Read `memory/semantic.md` ONCE to load project context before answering.

### On Every Turn

The preprompt hook handles reading `memory/working.md`.

### Task Files

Only load `/dev/[task]/*` files when actively working on that task.

### MCP Efficiency

Before calling any MCP tool to retrieve information, first check if that information might exist in `memory/semantic.md` or `dev/[task]/context.md` — local files are cheaper than remote MCP queries.

### Keep Context Minimal

Do not speculatively load files "just in case".

### Mid-Session Drift

If reasoning becomes uncertain or inconsistent with prior context, re-read `memory/semantic.md` before continuing.

{memory_discipline}

---

## Architecture

Before implementing a feature, read `{arch_file}`. It is the canonical record of architectural principles, load-bearing assumptions, and planned capabilities — not current build state (that lives in `memory/semantic.md`).
{skills_note}

---

## Key conventions

{conventions_md}

---

## Optional: Hermes Memory Mirroring

Hermes has its own `MEMORY.md` / `USER.md` persistence layer. These are complementary,
not replacements, for this project's `memory/` files. If you want high-signal lessons
visible inside Hermes's built-in persistence, you can symlink:

```bash
ln -s memory/semantic.md MEMORY.md
```

The project's `memory/semantic.md` remains the single source of truth.
"""


def referenced_memory_files() -> list[str]:
    """Return the set of .md files this adapter's Memory Discipline references."""
    return [
        "memory/semantic.md",
        "memory/working.md",
        "DECISIONS.md",
        "dev/[task]/context.md",
    ]


def _build_managed_content(config: dict) -> str:
    """Build the managed-section content from config."""
    skills = config.get("skills", {})
    arch_file = config.get("architecture", {}).get("file", "vision.md")
    conventions = config.get("conventions", [])
    conventions_md = (
        "\n".join(f"- {c}" for c in conventions) if conventions else ""
    )

    skills_note = ""
    if skills.get("enabled") and skills.get("standard"):
        skills_note = (
            f"\nThese skill files follow the {skills['standard']} standard —"
            " Hermes's `/skills` browser can enumerate them natively.\n"
        )

    return _MANAGED_TEMPLATE.format(
        arch_file=arch_file,
        skills_note=skills_note,
        conventions_md=conventions_md,
        memory_discipline=build_memory_discipline(config, arch_file),
    )


def generate(project_root: Path, config: dict) -> str:
    project = config["project"]
    managed_content = _build_managed_content(config)
    header = (
        f"# Project Context — {project['name']}\n\n"
        f"**{project['name']}** is {project['description']}"
    )

    agents_md_status = write_managed_section(
        project_root / "AGENTS.md", header, managed_content, "AGENTS.md"
    )

    return (
        "Hermes configuration generated:\n"
        f"{agents_md_status}\n\n"
        "Note: Hermes reads AGENTS.md natively.\n"
        "  Custom content outside <!-- amk:start/end --> is preserved."
    )


# ── Check mode ────────────────────────────────────────────────────────────────


def check(project_root: Path, config: dict) -> list[str]:
    """Return drift diffs for all managed files (empty if no drift)."""
    managed_content = _build_managed_content(config)
    result = check_managed_section(
        project_root / "AGENTS.md", managed_content, "AGENTS.md (hermes)"
    )
    return [result] if result else []
