"""
OpenClaw Adapter — generates .openclaw-system.md (system prompt include)

.openclaw-system.md structure:
  [project header + install options — written once on first create]

  <!-- amk:start -->
  <!-- GENERATED by agent-memory-kit. DO NOT EDIT MANAGED BLOCK DIRECTLY. -->
  [managed memory protocol + architecture ref + conventions + discipline]
  <!-- amk:end -->

  [custom content outside sentinels is preserved across regenerations]

OpenClaw has no native project-root file convention. Two install options:
  A) Point OpenClaw at this file via the `system_prompt_file` setting
  B) Paste the file contents directly into OpenClaw's system prompt settings
"""
from pathlib import Path

from .utils import write_managed_section, check_managed_section, build_memory_discipline


_MANAGED_TEMPLATE = """\
## Memory System

This project uses a file-based memory system. Treat it as authoritative.

### Startup (read in order)

1. `memory/semantic.md` — distilled project knowledge (≤500 lines); read ONCE per session
2. `memory/working.md` — live task state; read before every response

### On Every Turn

The preprompt hook handles reading `memory/working.md`.

### Task Files

Only load `/dev/[task]/*` files when actively working on that task.

### MCP Efficiency

Before calling any MCP tool to retrieve information, first check if that information might exist in `memory/semantic.md` or `dev/[task]/context.md` — local files are cheaper than remote MCP queries.

### Keep Context Minimal

Do not speculatively load files "just in case".

### Mid-Session Drift

If reasoning becomes uncertain or inconsistent with prior context, re-read `memory/semantic.md` before continuing.

---

## Architecture

Before implementing a feature, read `{arch_file}`. It is the canonical record of architectural principles, load-bearing assumptions, and planned capabilities — not current build state (that lives in `memory/semantic.md`).

---

## Key conventions

{conventions_md}

---

{memory_discipline}
"""


def referenced_memory_files() -> list[str]:
    """Return the set of .md files this adapter's Memory Discipline references."""
    return [
        "memory/semantic.md",
        "memory/working.md",
        "DECISIONS.md",
        "dev/[task]/context.md",
    ]


def _build_managed_content(config: dict) -> str:
    """Build the managed-section content from config."""
    arch_file = config.get("architecture", {}).get("file", "vision.md")
    conventions = config.get("conventions", [])
    conventions_md = "\n".join(f"- {c}" for c in conventions) if conventions else ""
    return _MANAGED_TEMPLATE.format(
        arch_file=arch_file,
        conventions_md=conventions_md,
        memory_discipline=build_memory_discipline(config, arch_file),
    )


def generate(project_root: Path, config: dict) -> str:
    """Generate OpenClaw configuration."""
    project = config["project"]
    managed_content = _build_managed_content(config)

    header = (
        f"# OpenClaw system prompt — {project['name']}\n\n"
        "<!--\n"
        "  Install options:\n"
        "    A) system_prompt_file: .openclaw-system.md  (in OpenClaw config)\n"
        "    B) Paste this file's content into OpenClaw's system prompt settings\n"
        "-->\n\n"
        f"You are an agent working in the **{project['name']}** project — {project['description']}"
    )

    status = write_managed_section(
        project_root / ".openclaw-system.md", header, managed_content, ".openclaw-system.md"
    )

    return (
        "OpenClaw configuration generated:\n"
        f"{status}\n\n"
        "Install options:\n"
        "  A) Set system_prompt_file: .openclaw-system.md in OpenClaw config\n"
        "  B) Paste the file contents into OpenClaw's system prompt settings"
    )


# ── Check mode ────────────────────────────────────────────────────────────────


def check(project_root: Path, config: dict) -> list[str]:
    """Return drift diffs for all managed files (empty if no drift)."""
    managed_content = _build_managed_content(config)
    result = check_managed_section(
        project_root / ".openclaw-system.md",
        managed_content,
        ".openclaw-system.md",
    )
    return [result] if result else []
