"""Shared adapter utilities."""
import difflib
from pathlib import Path
from typing import Optional


# ── Sentinels ─────────────────────────────────────────────────────────────────

SENTINEL_START = "<!-- amk:start -->"
SENTINEL_END = "<!-- amk:end -->"

# ── Generated banners (per file type) ─────────────────────────────────────────

GENERATED_BANNER_MD = (
    "<!-- GENERATED by agent-memory-kit. DO NOT EDIT MANAGED BLOCK DIRECTLY. -->"
)
GENERATED_BANNER_SH = "# Generated by agent-memory-kit. Do not edit directly."


# ── Gitignore ─────────────────────────────────────────────────────────────────

def ensure_gitignored(project_root: Path, entry: str) -> None:
    """Add entry to project .gitignore if not already present."""
    gitignore_path = project_root / ".gitignore"
    if gitignore_path.exists():
        content = gitignore_path.read_text()
        if entry in content.splitlines():
            return
        if not content.endswith("\n"):
            content += "\n"
        gitignore_path.write_text(content + entry + "\n")
    else:
        gitignore_path.write_text(entry + "\n")


# ── Managed-section (sentinel-based) write ────────────────────────────────────


def write_managed_section(
    file_path: Path,
    header: str,
    content: str,
    label: str,
    frontmatter: str = "",
) -> str:
    """Insert or replace an amk-managed block in a file.

    On first create: writes header (outside sentinel) + managed block.
    On re-run with sentinels present: replaces only the managed block.
    On file exists but no sentinels: appends the managed block.

    If *frontmatter* is provided (e.g. YAML frontmatter for Cursor rules),
    it is written once on first create and never touched again.

    Returns a human-readable status line.
    """
    banner_line = GENERATED_BANNER_MD + "\n"
    block = f"{SENTINEL_START}\n{banner_line}{content.rstrip()}\n{SENTINEL_END}\n"

    if not file_path.exists():
        body = f"{header}\n\n{block}" if not frontmatter else f"{frontmatter}\n{header}\n\n{block}"
        file_path.write_text(body)
        return f"  - {label} (created)"

    existing = file_path.read_text()
    start_idx = existing.find(SENTINEL_START)
    end_idx = existing.find(SENTINEL_END)

    if start_idx == -1 or end_idx == -1 or end_idx < start_idx:
        sep = "\n" if existing.endswith("\n") else "\n\n"
        file_path.write_text(existing + sep + block)
        return f"  - {label} (amk section appended — existing content preserved)"

    old_block = existing[start_idx : end_idx + len(SENTINEL_END)]
    new_block = block.rstrip("\n")

    if old_block == new_block:
        return f"  - {label} (unchanged)"

    updated = existing[:start_idx] + block + existing[end_idx + len(SENTINEL_END) :]
    file_path.write_text(updated)

    diff_lines = list(
        difflib.unified_diff(
            old_block.splitlines(keepends=True),
            new_block.splitlines(keepends=True),
            fromfile=f"{label} (before)",
            tofile=f"{label} (after)",
        )
    )
    return f"  - {label} (amk section updated)\n{''.join(diff_lines)}"


# ── Managed-section check (for --check) ───────────────────────────────────────


def check_managed_section(
    file_path: Path,
    expected_content: str,
    label: str,
) -> Optional[str]:
    """Check if a sentinel-managed file's managed block matches expected content.

    Returns None if the block matches (or file doesn't exist yet).
    Returns a unified diff string on mismatch.
    """
    if not file_path.exists():
        return f"{label}: file does not exist (not yet generated)"

    existing = file_path.read_text()
    start_idx = existing.find(SENTINEL_START)
    end_idx = existing.find(SENTINEL_END)

    if start_idx == -1 or end_idx == -1 or end_idx < start_idx:
        # No sentinel block — report the full file as needing generation
        return f"{label}: no managed block found (file needs initial generation)"

    banner_line = GENERATED_BANNER_MD + "\n"
    expected_block = f"{SENTINEL_START}\n{banner_line}{expected_content.rstrip()}\n{SENTINEL_END}"

    actual_block = existing[start_idx : end_idx + len(SENTINEL_END)]

    if actual_block == expected_block:
        return None

    diff_lines = list(
        difflib.unified_diff(
            actual_block.splitlines(keepends=True),
            expected_block.splitlines(keepends=True),
            fromfile=f"{label} (actual)",
            tofile=f"{label} (expected)",
        )
    )
    return "".join(diff_lines)


def check_fully_generated(
    file_path: Path,
    expected_content: str,
    label: str,
) -> Optional[str]:
    """Check if a fully-generated file matches expected content.

    Returns None if it matches (or file doesn't exist yet).
    Returns a unified diff string on mismatch.
    """
    if not file_path.exists():
        return f"{label}: file does not exist (not yet generated)"

    actual = file_path.read_text()
    if actual == expected_content:
        return None

    diff_lines = list(
        difflib.unified_diff(
            actual.splitlines(keepends=True),
            expected_content.splitlines(keepends=True),
            fromfile=f"{label} (actual)",
            tofile=f"{label} (expected)",
        )
    )
    return "".join(diff_lines)

# ── Approval Mode ────────────────────────────────────────────────────────────

# Canonical memory-file registry. Adding a file here is the ONLY edit needed
# to render it in Memory Discipline output across all adapters.
MEMORY_FILE_DESCRIPTORS = [
    {
        "path": "memory/semantic.md",
        "description": "current build state",
        "review_text": "propose updates; wait for approval before writing",
        "auto_text": "update directly after changes; summarize what you changed",
    },
    {
        "path": "memory/working.md",
        "description": "live task state",
        "review_text": "update freely after each response; no approval needed",
        "auto_text": "update freely after each response; no approval needed",
    },
    {
        "path": "DECISIONS.md",
        "description": "append-only log of architectural decisions",
        "review_text": "propose entries for approval",
        "auto_text": "update directly after changes; summarize new entries",
    },
    {
        "path": "dev/[task]/context.md",
        "description": "log confirmed assumptions immediately",
        "review_text": "no approval needed",
        "auto_text": "no approval needed",
    },
    {
        "path": "memory/candidates.md",
        "description": "staged lessons awaiting promotion; append-only, one heading per claim",
        "review_text": "append candidate claims with source pointers; never edit existing entries",
        "auto_text": "append candidate claims with source pointers; never edit existing entries",
    },
    {
        "path": "memory/candidates.rejected.md",
        "description": "promoted-by-move from candidates.md; each entry includes a Why rejected: reason",
        "review_text": "move entries from candidates.md with Why rejected: appended",
        "auto_text": "move entries from candidates.md with Why rejected: appended",
    },
]

# Files that have their own contract and never appear in approval_mode.
# arch_file (vision.md) is rendered separately because its prose differs.
EXCLUDED_FROM_APPROVAL_MODE = {"vision.md"}


# Files that are always auto regardless of approval_mode config.
# Candidates are staging areas — the human gate is at promotion, not append.
ALWAYS_AUTO = {
    "memory/working.md",
    "dev/[task]/context.md",
    "memory/candidates.md",
    "memory/candidates.rejected.md",
}


def mode_for(path: str, config: dict) -> str:
    """Return 'review' or 'auto' for a memory file path based on config."""
    if path in ALWAYS_AUTO:
        return "auto"
    approval = config.get("memory", {}).get("approval_mode", {})
    default_mode = approval.get("default", "review")
    review_list = approval.get("review", [])
    return "review" if path in review_list else default_mode


def build_memory_discipline(config: dict, arch_file: str) -> str:
    """Build Memory Discipline markdown from config.approval_mode + descriptors.

    Emits a self-contained block starting with ``### Memory Discipline``.
    Adapters place this block where a level-3 heading fits their document.
    """
    bullets = []
    for d in MEMORY_FILE_DESCRIPTORS:
        text = d["review_text"] if mode_for(d["path"], config) == "review" else d["auto_text"]
        bullets.append(f"- `{d['path']}` — {d['description']}; {text}")

    # arch_file rendered separately — its semantics aren't governed by approval_mode
    arch_bullet = (
        f"- `{arch_file}` — principles, load-bearing assumptions, planned capabilities; "
        "update only on merge when a capability ships or an assumption is invalidated; "
        "**never put current state here** (that's `semantic.md`), **never put planning details here** "
        "(tickets, checklists, phases)"
    )
    # Insert arch_file bullet before dev/[task]/context.md to match current ordering
    bullets.insert(-1, arch_bullet)

    return "### Memory Discipline\n\n" + "\n".join(bullets) + f"""

**DECISIONS.md vs. Assumptions distinction:**
- `DECISIONS.md` = immutable log — "we chose X on date Y because Z" — never edited, only superseded by appending
- `{arch_file}` Assumptions = live load-bearing premises — mutable; when invalidated, append a supersession to `DECISIONS.md` first, then update the assumption

**On PR merge:** check `{arch_file}` — move shipped capabilities to `memory/semantic.md` and remove them from the Vision section; append a supersession to `DECISIONS.md` then update or remove any invalidated Assumption.

**Stage → Graduate promotion (#11):**
- `memory/candidates.md` — append-only staging queue. Each entry is a `###` heading claim with a `- Staged: YYYY-MM-DD` date and a `- Sources:` bullet list (commit hashes, session refs, or file:line pointers). Before appending, grep candidates.md for matching claims — if found, append a source bullet to the existing heading instead of creating a duplicate. One heading per claim.
- `memory/semantic.md` — on promotion, move the entire heading block from candidates.md into semantic.md with a one-line `**Why accepted:**` rationale appended. The candidate entry disappears from candidates.md.
- `memory/candidates.rejected.md` — on rejection, move the heading block here with a one-line `**Why rejected:**` reason. Preserves the churn history to prevent re-litigation.
- All promotions and rejections are committed separately with `promote:` or `reject:` commit message prefixes. The diff *is* the audit trail."""


def build_approval_gate(config: dict) -> str:
    """Build the Approval Gate rule section for Antigravity templates."""
    sem = mode_for("memory/semantic.md", config)
    dec = mode_for("DECISIONS.md", config)

    if sem == "review" or dec == "review":
        lines = ["## Approval Gate"]
        if sem == "review":
            lines.append("- `memory/semantic.md` requires explicit user approval before writing.")
        else:
            lines.append("- `memory/semantic.md` may be updated directly; summarize changes.")
        if dec == "review":
            lines.append("- `DECISIONS.md` requires explicit user approval before writing.")
        else:
            lines.append("- `DECISIONS.md` may be updated directly; summarize new entries.")
        lines.append("- `memory/working.md` may be updated freely, including rewriting from scratch if stale.")
        lines.append("- Never write speculatively to files that require approval.")
        return "\n".join(lines)
    else:
        return (
            "## Approval Gate\n\n"
            "All memory files may be updated directly. Summarize what changed.\n"
            "- `memory/working.md` may be updated freely, including rewriting from scratch if stale."
        )


# Frozen at v3 release — files that default to 'review' under backward compat.
COMPAT_REVIEW_DEFAULTS = {"memory/semantic.md", "DECISIONS.md"}


def validate_approval_mode(config: dict, referenced_files: set[str]) -> list[str]:
    """Validate approval_mode coverage. Returns list of drift/info messages.

    DRIFT messages (real problems) cause --check to exit non-zero.
    INFO messages go to stderr but exit 0 — they are nudges, not blockers.
    """
    approval = config.get("memory", {}).get("approval_mode")
    review_list = set((approval or {}).get("review", []))
    known_paths = {d["path"] for d in MEMORY_FILE_DESCRIPTORS}
    checkable = referenced_files - EXCLUDED_FROM_APPROVAL_MODE

    msgs = []

    # 1. Adapter declared a file the registry doesn't know about
    for path in sorted(checkable - known_paths):
        msgs.append(
            f"DRIFT registry: {path} declared in adapter referenced_memory_files() "
            f"but missing from MEMORY_FILE_DESCRIPTORS in utils.py"
        )

    # 2. Stale review entry — no adapter uses it
    for path in sorted(review_list - checkable):
        msgs.append(
            f"DRIFT config: {path} in approval_mode.review but no adapter references it"
        )

    # 3. Compat-default scope notice
    if approval is None:
        unknown_to_compat = checkable - COMPAT_REVIEW_DEFAULTS - ALWAYS_AUTO
        if unknown_to_compat:
            msgs.append(
                f"INFO compat: approval_mode unset; these files default to 'auto' under compat "
                f"({sorted(unknown_to_compat)}) — set approval_mode explicitly to confirm."
            )

    return msgs
