#!/bin/bash
# stop.sh — capture levels: merge
# Generated by agent-memory-kit. Do not edit directly.
set -euo pipefail

emit_memory_reminder() {
  echo "Memory check — inspect diff and propose updates if significant:"
  echo "- working.md: update current state (no approval needed)"
  echo "- semantic.md: update directly; summarize changes"
  echo "- DECISIONS.md: update directly; summarize changes"
  echo "- If intent unclear from diff, ask before proposing"
}

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || echo .)"

# commit / merge level — scan all commits since last hook run
SENTINEL="$REPO_ROOT/.agent/.last_checked_commit"
PREV_HEAD="$(cat "$SENTINEL" 2>/dev/null || true)"
CURRENT_HEAD="$(git -C "$REPO_ROOT" rev-parse HEAD 2>/dev/null || true)"

if [ -n "$PREV_HEAD" ] && [ -n "$CURRENT_HEAD" ] && [ "$CURRENT_HEAD" != "$PREV_HEAD" ]; then
  HAS_COMMIT=false
  HAS_MERGE=false

  # Use range scan if PREV_HEAD is still an ancestor; fall back to HEAD only on rebase/reset
  if git -C "$REPO_ROOT" merge-base --is-ancestor "$PREV_HEAD" "$CURRENT_HEAD" 2>/dev/null; then
    RANGE_COMMITS="$(git -C "$REPO_ROOT" rev-list "$PREV_HEAD..$CURRENT_HEAD" 2>/dev/null || true)"
  else
    RANGE_COMMITS="$CURRENT_HEAD"
  fi

  for C in $RANGE_COMMITS; do
    # rev-list --parents outputs: <sha> <p1> [<p2> ...]; wc -w - 1 = parent count
    WORDS="$(git -C "$REPO_ROOT" rev-list --parents -n 1 "$C" 2>/dev/null | wc -w)"
    PARENTS=$((WORDS - 1))
    if [ "$PARENTS" -ge 2 ]; then HAS_MERGE=true; else HAS_COMMIT=true; fi
  done

  if [ "$HAS_MERGE" = "true" ]; then
    echo "Merge commit detected — review architectural impact:"
    emit_memory_reminder
  fi
fi

# Update sentinel
CURRENT_HEAD="$(git -C "$REPO_ROOT" rev-parse HEAD 2>/dev/null || true)"
if [ -n "$CURRENT_HEAD" ]; then
  mkdir -p "$REPO_ROOT/.agent"
  echo "$CURRENT_HEAD" > "$SENTINEL"
fi
